language: bash

services:
  - docker

env:
  - ARCH=x86
#  - ARCH=arm

script:
  - chmod -R 777 *
  - bash docker/build.sh

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    repo: rok4/rok4
    tags: true
